//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenealogyResearchApp.GRAppLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLine
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public string JSON { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
