//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRAppLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Events = new HashSet<Event>();
            this.EventsAttended = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string FirstnameRaw { get; set; }
        public string MiddlenameRaw { get; set; }
        public string LastnameRaw { get; set; }
        public Nullable<int> FirstNameId { get; set; }
        public Nullable<int> MiddleNameId { get; set; }
        public Nullable<int> LastNameId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<int> BirthPlaceId { get; set; }
        public Nullable<int> DeathPlaceId { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<int> MotherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Name FirstName { get; set; }
        public virtual Name LastName { get; set; }
        public virtual Name MiddleName { get; set; }
        public virtual Place DeathPlace { get; set; }
        public virtual Place BirthPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> EventsAttended { get; set; }
        public virtual Person Father { get; set; }
        public virtual Person Mother { get; set; }
    }
}
